name: tests

on: [push, pull_request]

jobs:

  test_selene:
    name: test_selene
    runs-on: ubuntu-20.04
    env:
      DISPLAY: ":99"
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Install Chrome & xvfb
        run: |
          sudo apt-get install google-chrome-stable xvfb
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: pytest test_selene.py
        run: |
          poetry run pytest --tb=no tests/test_selene.py

  test_native_selenium:
    name: test_native_selenium
    runs-on: ubuntu-20.04
    env:
      DISPLAY: ":99"
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Install Chrome & xvfb
        run: |
          sudo apt-get install google-chrome-stable xvfb
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: pytest test_native_selenium.py
        run: |
          poetry run pytest --tb=no tests/test_native_selenium.py
